name: Build & Test reutilizable

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
    - name: Cache de paquetes maven
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ubuntu-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ubuntu-maven
    - name: Build and test
      run: ./mvnw clean verify
    - name: Compilación
      run: ./mvnw clean package -DskipTests
    - name: Upload de JAR a workflow artifacts
      uses: actions/upload-artifact@v4
      with:
        name: springboot-app
        path: target/*.jar
