name: CI con Matrix builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [17, 21]
    name: Pruebas de Java ${{ matrix.java }} en ${{ matrix.os }}
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Cache de paquetes Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{hashFiles('**/pom.xml')}}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build y Test
      run: ./mvnw clean verify
