name: CI – Ejemplo Spring Boot
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/build-test-reusable.yml
    with:
      java-version: '25'
  deploy-staging:
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v4
    - name: compilar JAR
      run: ./mvnw clean package -DskipTests
    - name: Deploy a staging
      run: |
        echo "Deploy a STAGING en curso..."
#        curl -X POST https://staging.pepe.com/deploy \
#        -H "Authorization: Bearer ${{ secrets.STAGING_TOKEN }}"
  deploy-prod:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
#      name: production
#      url: https://miservidorapi.com
    steps:
    - uses: actions/checkout@v4
    - name: compilar JAR
      run: ./mvnw clean package -DskipTests
    - name: Deploy a staging
      run: |
        echo "Deploy a STAGING en curso..."
