name: CI producción

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Log en Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password:  ${{ secrets.DOCKER_PASSWORD }}
    - name: Crear imagen Docker
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/mi_imagen:latest .
    - name: Push a Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mi_imagen:latest
#    - name: Deploy a srver
#      run: scp target/*.jar pepe@192.168.1.123:/ruta/destino
#      env:
#        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
