name: CI producción

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -DskipTests
#    - name: Deploy a srver
#      run: scp target/*.jar pepe@192.168.1.123:/ruta/destino
#      env:
#        SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
